pub const PCE_NTSC_COLORBURST_CLOCK_HZ_NUMERATOR: u64 = 315_000_000;
pub const PCE_NTSC_COLORBURST_CLOCK_HZ_DENOMINATOR: u64 = 88;
pub const PCE_NTSC_MASTER_CLOCK_COLORBURST_MULTIPLIER: u64 = 6;
pub const PCE_NTSC_MASTER_CLOCK_HZ_NUMERATOR: u64 =
    PCE_NTSC_COLORBURST_CLOCK_HZ_NUMERATOR * PCE_NTSC_MASTER_CLOCK_COLORBURST_MULTIPLIER;
pub const PCE_NTSC_MASTER_CLOCK_HZ_DENOMINATOR: u64 = PCE_NTSC_COLORBURST_CLOCK_HZ_DENOMINATOR;
pub const PCE_DEFAULT_AUDIO_SAMPLE_RATE_HZ: u32 = 44_100;
pub const PCE_PHYSICAL_WORK_RAM_START: u32 = 0x1F_0000;
pub const PCE_PHYSICAL_WORK_RAM_END: u32 = 0x1F_7FFF;

pub const PCE_NTSC_REFERENCE_MHZ_NUMERATOR: u64 =
    PCE_NTSC_COLORBURST_CLOCK_HZ_NUMERATOR / 1_000_000;
pub const PCE_NTSC_REFERENCE_MHZ_DENOMINATOR: u64 = PCE_NTSC_COLORBURST_CLOCK_HZ_DENOMINATOR;
pub const PCE_MASTER_CLOCK_NTSC_REFERENCE_MULTIPLIER: u64 =
    PCE_NTSC_MASTER_CLOCK_COLORBURST_MULTIPLIER;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn master_clock_is_derived_from_the_ntsc_colorburst_reference() {
        assert_eq!(PCE_NTSC_COLORBURST_CLOCK_HZ_NUMERATOR, 315_000_000);
        assert_eq!(PCE_NTSC_COLORBURST_CLOCK_HZ_DENOMINATOR, 88);
        assert_eq!(PCE_NTSC_MASTER_CLOCK_HZ_NUMERATOR, 1_890_000_000);
        assert_eq!(PCE_NTSC_MASTER_CLOCK_HZ_DENOMINATOR, 88);
        assert_eq!(
            PCE_NTSC_MASTER_CLOCK_HZ_NUMERATOR,
            PCE_NTSC_COLORBURST_CLOCK_HZ_NUMERATOR * PCE_NTSC_MASTER_CLOCK_COLORBURST_MULTIPLIER
        );
        assert_eq!(
            PCE_NTSC_MASTER_CLOCK_HZ_DENOMINATOR,
            PCE_NTSC_COLORBURST_CLOCK_HZ_DENOMINATOR
        );
        assert_eq!(
            PCE_NTSC_REFERENCE_MHZ_NUMERATOR
                * 1_000_000
                * PCE_MASTER_CLOCK_NTSC_REFERENCE_MULTIPLIER,
            PCE_NTSC_MASTER_CLOCK_HZ_NUMERATOR
        );
        assert_eq!(
            PCE_NTSC_REFERENCE_MHZ_DENOMINATOR,
            PCE_NTSC_MASTER_CLOCK_HZ_DENOMINATOR
        );
    }
}
