use crate::hardware::bus::Bus;
use crate::hardware::cpu::Cpu;

pub fn unimplemented_handler(cpu: &mut Cpu, opcode: u8) {
    log::warn!(
        "Unimplemented opcode {:02X} at PC={:04X}",
        opcode,
        cpu.pc.wrapping_sub(1)
    );
}

pub fn execute_opcode(cpu: &mut Cpu, bus: &mut Bus, opcode: u8) -> u8 {
    use crate::hardware::opcodes::unofficial as unoff;

    match opcode {
        0x00 => { crate::hardware::opcodes::flow::brk(cpu, bus); 0 }
        0x01 => { crate::hardware::opcodes::bitwise::ora_ind_x(cpu, bus); 0 }
        0x02 => { unoff::kil(cpu, bus); 0 }
        0x03 => { unoff::slo_ind_x(cpu, bus); 0 }
        0x04 => { unoff::nop_zp(cpu, bus); 0 }
        0x05 => { crate::hardware::opcodes::bitwise::ora_zp(cpu, bus); 0 }
        0x06 => { crate::hardware::opcodes::bitwise::asl_zp(cpu, bus); 0 }
        0x07 => { unoff::slo_zp(cpu, bus); 0 }
        0x08 => { crate::hardware::opcodes::load::php(cpu, bus); 0 }
        0x09 => { crate::hardware::opcodes::bitwise::ora_imm(cpu, bus); 0 }
        0x0A => { crate::hardware::opcodes::bitwise::asl_acc(cpu, bus); 0 }
        0x0B => { unoff::anc(cpu, bus); 0 }
        0x0C => { unoff::nop_abs(cpu, bus); 0 }
        0x0D => { crate::hardware::opcodes::bitwise::ora_abs(cpu, bus); 0 }
        0x0E => { crate::hardware::opcodes::bitwise::asl_abs(cpu, bus); 0 }
        0x0F => { unoff::slo_abs(cpu, bus); 0 }
        0x10 => crate::hardware::opcodes::flow::bpl(cpu, bus),
        0x11 => crate::hardware::opcodes::bitwise::ora_ind_y(cpu, bus),
        0x12 => { unoff::kil(cpu, bus); 0 }
        0x13 => { unoff::slo_ind_y(cpu, bus); 0 }
        0x14 => { unoff::nop_zp_x(cpu, bus); 0 }
        0x15 => { crate::hardware::opcodes::bitwise::ora_zp_x(cpu, bus); 0 }
        0x16 => { crate::hardware::opcodes::bitwise::asl_zp_x(cpu, bus); 0 }
        0x17 => { unoff::slo_zp_x(cpu, bus); 0 }
        0x18 => { crate::hardware::opcodes::flow::clc(cpu, bus); 0 }
        0x19 => crate::hardware::opcodes::bitwise::ora_abs_y(cpu, bus),
        0x1A => { unoff::nop_implied(cpu, bus); 0 }
        0x1B => { unoff::slo_abs_y(cpu, bus); 0 }
        0x1C => unoff::nop_abs_x(cpu, bus),
        0x1D => crate::hardware::opcodes::bitwise::ora_abs_x(cpu, bus),
        0x1E => { crate::hardware::opcodes::bitwise::asl_abs_x(cpu, bus); 0 }
        0x1F => { unoff::slo_abs_x(cpu, bus); 0 }
        0x20 => { crate::hardware::opcodes::flow::jsr(cpu, bus); 0 }
        0x21 => { crate::hardware::opcodes::bitwise::and_ind_x(cpu, bus); 0 }
        0x22 => { unoff::kil(cpu, bus); 0 }
        0x23 => { unoff::rla_ind_x(cpu, bus); 0 }
        0x24 => { crate::hardware::opcodes::bitwise::bit_zp(cpu, bus); 0 }
        0x25 => { crate::hardware::opcodes::bitwise::and_zp(cpu, bus); 0 }
        0x26 => { crate::hardware::opcodes::bitwise::rol_zp(cpu, bus); 0 }
        0x27 => { unoff::rla_zp(cpu, bus); 0 }
        0x28 => { crate::hardware::opcodes::load::plp(cpu, bus); 0 }
        0x29 => { crate::hardware::opcodes::bitwise::and_imm(cpu, bus); 0 }
        0x2A => { crate::hardware::opcodes::bitwise::rol_acc(cpu, bus); 0 }
        0x2B => { unoff::anc(cpu, bus); 0 }
        0x2C => { crate::hardware::opcodes::bitwise::bit_abs(cpu, bus); 0 }
        0x2D => { crate::hardware::opcodes::bitwise::and_abs(cpu, bus); 0 }
        0x2E => { crate::hardware::opcodes::bitwise::rol_abs(cpu, bus); 0 }
        0x2F => { unoff::rla_abs(cpu, bus); 0 }
        0x30 => crate::hardware::opcodes::flow::bmi(cpu, bus),
        0x31 => crate::hardware::opcodes::bitwise::and_ind_y(cpu, bus),
        0x32 => { unoff::kil(cpu, bus); 0 }
        0x33 => { unoff::rla_ind_y(cpu, bus); 0 }
        0x34 => { unoff::nop_zp_x(cpu, bus); 0 }
        0x35 => { crate::hardware::opcodes::bitwise::and_zp_x(cpu, bus); 0 }
        0x36 => { crate::hardware::opcodes::bitwise::rol_zp_x(cpu, bus); 0 }
        0x37 => { unoff::rla_zp_x(cpu, bus); 0 }
        0x38 => { crate::hardware::opcodes::flow::sec(cpu, bus); 0 }
        0x39 => crate::hardware::opcodes::bitwise::and_abs_y(cpu, bus),
        0x3A => { unoff::nop_implied(cpu, bus); 0 }
        0x3B => { unoff::rla_abs_y(cpu, bus); 0 }
        0x3C => unoff::nop_abs_x(cpu, bus),
        0x3D => crate::hardware::opcodes::bitwise::and_abs_x(cpu, bus),
        0x3E => { crate::hardware::opcodes::bitwise::rol_abs_x(cpu, bus); 0 }
        0x3F => { unoff::rla_abs_x(cpu, bus); 0 }
        0x40 => { crate::hardware::opcodes::flow::rti(cpu, bus); 0 }
        0x41 => { crate::hardware::opcodes::bitwise::eor_ind_x(cpu, bus); 0 }
        0x42 => { unoff::kil(cpu, bus); 0 }
        0x43 => { unoff::sre_ind_x(cpu, bus); 0 }
        0x44 => { unoff::nop_zp(cpu, bus); 0 }
        0x45 => { crate::hardware::opcodes::bitwise::eor_zp(cpu, bus); 0 }
        0x46 => { crate::hardware::opcodes::bitwise::lsr_zp(cpu, bus); 0 }
        0x47 => { unoff::sre_zp(cpu, bus); 0 }
        0x48 => { crate::hardware::opcodes::load::pha(cpu, bus); 0 }
        0x49 => { crate::hardware::opcodes::bitwise::eor_imm(cpu, bus); 0 }
        0x4A => { crate::hardware::opcodes::bitwise::lsr_acc(cpu, bus); 0 }
        0x4B => { unoff::alr(cpu, bus); 0 }
        0x4C => { crate::hardware::opcodes::flow::jmp_abs(cpu, bus); 0 }
        0x4D => { crate::hardware::opcodes::bitwise::eor_abs(cpu, bus); 0 }
        0x4E => { crate::hardware::opcodes::bitwise::lsr_abs(cpu, bus); 0 }
        0x4F => { unoff::sre_abs(cpu, bus); 0 }
        0x50 => crate::hardware::opcodes::flow::bvc(cpu, bus),
        0x51 => crate::hardware::opcodes::bitwise::eor_ind_y(cpu, bus),
        0x52 => { unoff::kil(cpu, bus); 0 }
        0x53 => { unoff::sre_ind_y(cpu, bus); 0 }
        0x54 => { unoff::nop_zp_x(cpu, bus); 0 }
        0x55 => { crate::hardware::opcodes::bitwise::eor_zp_x(cpu, bus); 0 }
        0x56 => { crate::hardware::opcodes::bitwise::lsr_zp_x(cpu, bus); 0 }
        0x57 => { unoff::sre_zp_x(cpu, bus); 0 }
        0x58 => { crate::hardware::opcodes::flow::cli(cpu, bus); 0 }
        0x59 => crate::hardware::opcodes::bitwise::eor_abs_y(cpu, bus),
        0x5A => { unoff::nop_implied(cpu, bus); 0 }
        0x5B => { unoff::sre_abs_y(cpu, bus); 0 }
        0x5C => unoff::nop_abs_x(cpu, bus),
        0x5D => crate::hardware::opcodes::bitwise::eor_abs_x(cpu, bus),
        0x5E => { crate::hardware::opcodes::bitwise::lsr_abs_x(cpu, bus); 0 }
        0x5F => { unoff::sre_abs_x(cpu, bus); 0 }
        0x60 => { crate::hardware::opcodes::flow::rts(cpu, bus); 0 }
        0x61 => { crate::hardware::opcodes::alu::adc_ind_x(cpu, bus); 0 }
        0x62 => { unoff::kil(cpu, bus); 0 }
        0x63 => { unoff::rra_ind_x(cpu, bus); 0 }
        0x64 => { unoff::nop_zp(cpu, bus); 0 }
        0x65 => { crate::hardware::opcodes::alu::adc_zp(cpu, bus); 0 }
        0x66 => { crate::hardware::opcodes::bitwise::ror_zp(cpu, bus); 0 }
        0x67 => { unoff::rra_zp(cpu, bus); 0 }
        0x68 => { crate::hardware::opcodes::load::pla(cpu, bus); 0 }
        0x69 => { crate::hardware::opcodes::alu::adc_imm(cpu, bus); 0 }
        0x6A => { crate::hardware::opcodes::bitwise::ror_acc(cpu, bus); 0 }
        0x6B => { unoff::arr(cpu, bus); 0 }
        0x6C => { crate::hardware::opcodes::flow::jmp_ind(cpu, bus); 0 }
        0x6D => { crate::hardware::opcodes::alu::adc_abs(cpu, bus); 0 }
        0x6E => { crate::hardware::opcodes::bitwise::ror_abs(cpu, bus); 0 }
        0x6F => { unoff::rra_abs(cpu, bus); 0 }
        0x70 => crate::hardware::opcodes::flow::bvs(cpu, bus),
        0x71 => crate::hardware::opcodes::alu::adc_ind_y(cpu, bus),
        0x72 => { unoff::kil(cpu, bus); 0 }
        0x73 => { unoff::rra_ind_y(cpu, bus); 0 }
        0x74 => { unoff::nop_zp_x(cpu, bus); 0 }
        0x75 => { crate::hardware::opcodes::alu::adc_zp_x(cpu, bus); 0 }
        0x76 => { crate::hardware::opcodes::bitwise::ror_zp_x(cpu, bus); 0 }
        0x77 => { unoff::rra_zp_x(cpu, bus); 0 }
        0x78 => { crate::hardware::opcodes::flow::sei(cpu, bus); 0 }
        0x79 => crate::hardware::opcodes::alu::adc_abs_y(cpu, bus),
        0x7A => { unoff::nop_implied(cpu, bus); 0 }
        0x7B => { unoff::rra_abs_y(cpu, bus); 0 }
        0x7C => unoff::nop_abs_x(cpu, bus),
        0x7D => crate::hardware::opcodes::alu::adc_abs_x(cpu, bus),
        0x7E => { crate::hardware::opcodes::bitwise::ror_abs_x(cpu, bus); 0 }
        0x7F => { unoff::rra_abs_x(cpu, bus); 0 }
        0x80 => { crate::hardware::opcodes::flow::nop_imm(cpu, bus); 0 }
        0x81 => { crate::hardware::opcodes::load::sta_ind_x(cpu, bus); 0 }
        0x82 => { crate::hardware::opcodes::flow::nop_imm(cpu, bus); 0 }
        0x83 => { unoff::sax_ind_x(cpu, bus); 0 }
        0x84 => { crate::hardware::opcodes::load::sty_zp(cpu, bus); 0 }
        0x85 => { crate::hardware::opcodes::load::sta_zp(cpu, bus); 0 }
        0x86 => { crate::hardware::opcodes::load::stx_zp(cpu, bus); 0 }
        0x87 => { unoff::sax_zp(cpu, bus); 0 }
        0x88 => { crate::hardware::opcodes::alu::dey(cpu, bus); 0 }
        0x89 => { crate::hardware::opcodes::flow::nop_imm(cpu, bus); 0 }
        0x8A => { crate::hardware::opcodes::load::txa(cpu, bus); 0 }
        0x8B => { unimplemented_handler(cpu, opcode); 0 } // ANE/XAA — highly unstable
        0x8C => { crate::hardware::opcodes::load::sty_abs(cpu, bus); 0 }
        0x8D => { crate::hardware::opcodes::load::sta_abs(cpu, bus); 0 }
        0x8E => { crate::hardware::opcodes::load::stx_abs(cpu, bus); 0 }
        0x8F => { unoff::sax_abs(cpu, bus); 0 }
        0x90 => crate::hardware::opcodes::flow::bcc(cpu, bus),
        0x91 => { crate::hardware::opcodes::load::sta_ind_y(cpu, bus); 0 }
        0x92 => { unoff::kil(cpu, bus); 0 }
        0x93 => { unimplemented_handler(cpu, opcode); 0 } // SHA (ind),Y — unstable
        0x94 => { crate::hardware::opcodes::load::sty_zp_x(cpu, bus); 0 }
        0x95 => { crate::hardware::opcodes::load::sta_zp_x(cpu, bus); 0 }
        0x96 => { crate::hardware::opcodes::load::stx_zp_y(cpu, bus); 0 }
        0x97 => { unoff::sax_zp_y(cpu, bus); 0 }
        0x98 => { crate::hardware::opcodes::load::tya(cpu, bus); 0 }
        0x99 => { crate::hardware::opcodes::load::sta_abs_y(cpu, bus); 0 }
        0x9A => { crate::hardware::opcodes::load::txs(cpu, bus); 0 }
        0x9B => { unimplemented_handler(cpu, opcode); 0 } // TAS — unstable
        0x9C => { unimplemented_handler(cpu, opcode); 0 } // SHY — unstable
        0x9D => { crate::hardware::opcodes::load::sta_abs_x(cpu, bus); 0 }
        0x9E => { unimplemented_handler(cpu, opcode); 0 } // SHX — unstable
        0x9F => { unimplemented_handler(cpu, opcode); 0 } // SHA abs,Y — unstable
        0xA0 => { crate::hardware::opcodes::load::ldy_imm(cpu, bus); 0 }
        0xA1 => { crate::hardware::opcodes::load::lda_ind_x(cpu, bus); 0 }
        0xA2 => { crate::hardware::opcodes::load::ldx_imm(cpu, bus); 0 }
        0xA3 => { unoff::lax_ind_x(cpu, bus); 0 }
        0xA4 => { crate::hardware::opcodes::load::ldy_zp(cpu, bus); 0 }
        0xA5 => { crate::hardware::opcodes::load::lda_zp(cpu, bus); 0 }
        0xA6 => { crate::hardware::opcodes::load::ldx_zp(cpu, bus); 0 }
        0xA7 => { unoff::lax_zp(cpu, bus); 0 }
        0xA8 => { crate::hardware::opcodes::load::tay(cpu, bus); 0 }
        0xA9 => { crate::hardware::opcodes::load::lda_imm(cpu, bus); 0 }
        0xAA => { crate::hardware::opcodes::load::tax(cpu, bus); 0 }
        0xAB => { unimplemented_handler(cpu, opcode); 0 } // LAX #imm — unstable
        0xAC => { crate::hardware::opcodes::load::ldy_abs(cpu, bus); 0 }
        0xAD => { crate::hardware::opcodes::load::lda_abs(cpu, bus); 0 }
        0xAE => { crate::hardware::opcodes::load::ldx_abs(cpu, bus); 0 }
        0xAF => { unoff::lax_abs(cpu, bus); 0 }
        0xB0 => crate::hardware::opcodes::flow::bcs(cpu, bus),
        0xB1 => crate::hardware::opcodes::load::lda_ind_y(cpu, bus),
        0xB2 => { unoff::kil(cpu, bus); 0 }
        0xB3 => unoff::lax_ind_y(cpu, bus),
        0xB4 => { crate::hardware::opcodes::load::ldy_zp_x(cpu, bus); 0 }
        0xB5 => { crate::hardware::opcodes::load::lda_zp_x(cpu, bus); 0 }
        0xB6 => { crate::hardware::opcodes::load::ldx_zp_y(cpu, bus); 0 }
        0xB7 => { unoff::lax_zp_y(cpu, bus); 0 }
        0xB8 => { crate::hardware::opcodes::flow::clv(cpu, bus); 0 }
        0xB9 => crate::hardware::opcodes::load::lda_abs_y(cpu, bus),
        0xBA => { crate::hardware::opcodes::load::tsx(cpu, bus); 0 }
        0xBB => { unimplemented_handler(cpu, opcode); 0 } // LAS — unstable
        0xBC => crate::hardware::opcodes::load::ldy_abs_x(cpu, bus),
        0xBD => crate::hardware::opcodes::load::lda_abs_x(cpu, bus),
        0xBE => crate::hardware::opcodes::load::ldx_abs_y(cpu, bus),
        0xBF => unoff::lax_abs_y(cpu, bus),
        0xC0 => { crate::hardware::opcodes::alu::cpy_imm(cpu, bus); 0 }
        0xC1 => { crate::hardware::opcodes::alu::cmp_ind_x(cpu, bus); 0 }
        0xC2 => { crate::hardware::opcodes::flow::nop_imm(cpu, bus); 0 }
        0xC3 => { unoff::dcp_ind_x(cpu, bus); 0 }
        0xC4 => { crate::hardware::opcodes::alu::cpy_zp(cpu, bus); 0 }
        0xC5 => { crate::hardware::opcodes::alu::cmp_zp(cpu, bus); 0 }
        0xC6 => { crate::hardware::opcodes::alu::dec_zp(cpu, bus); 0 }
        0xC7 => { unoff::dcp_zp(cpu, bus); 0 }
        0xC8 => { crate::hardware::opcodes::alu::iny(cpu, bus); 0 }
        0xC9 => { crate::hardware::opcodes::alu::cmp_imm(cpu, bus); 0 }
        0xCA => { crate::hardware::opcodes::alu::dex(cpu, bus); 0 }
        0xCB => { unoff::axs(cpu, bus); 0 }
        0xCC => { crate::hardware::opcodes::alu::cpy_abs(cpu, bus); 0 }
        0xCD => { crate::hardware::opcodes::alu::cmp_abs(cpu, bus); 0 }
        0xCE => { crate::hardware::opcodes::alu::dec_abs(cpu, bus); 0 }
        0xCF => { unoff::dcp_abs(cpu, bus); 0 }
        0xD0 => crate::hardware::opcodes::flow::bne(cpu, bus),
        0xD1 => crate::hardware::opcodes::alu::cmp_ind_y(cpu, bus),
        0xD2 => { unoff::kil(cpu, bus); 0 }
        0xD3 => { unoff::dcp_ind_y(cpu, bus); 0 }
        0xD4 => { unoff::nop_zp_x(cpu, bus); 0 }
        0xD5 => { crate::hardware::opcodes::alu::cmp_zp_x(cpu, bus); 0 }
        0xD6 => { crate::hardware::opcodes::alu::dec_zp_x(cpu, bus); 0 }
        0xD7 => { unoff::dcp_zp_x(cpu, bus); 0 }
        0xD8 => { crate::hardware::opcodes::flow::cld(cpu, bus); 0 }
        0xD9 => crate::hardware::opcodes::alu::cmp_abs_y(cpu, bus),
        0xDA => { unoff::nop_implied(cpu, bus); 0 }
        0xDB => { unoff::dcp_abs_y(cpu, bus); 0 }
        0xDC => unoff::nop_abs_x(cpu, bus),
        0xDD => crate::hardware::opcodes::alu::cmp_abs_x(cpu, bus),
        0xDE => { crate::hardware::opcodes::alu::dec_abs_x(cpu, bus); 0 }
        0xDF => { unoff::dcp_abs_x(cpu, bus); 0 }
        0xE0 => { crate::hardware::opcodes::alu::cpx_imm(cpu, bus); 0 }
        0xE1 => { crate::hardware::opcodes::alu::sbc_ind_x(cpu, bus); 0 }
        0xE2 => { crate::hardware::opcodes::flow::nop_imm(cpu, bus); 0 }
        0xE3 => { unoff::isb_ind_x(cpu, bus); 0 }
        0xE4 => { crate::hardware::opcodes::alu::cpx_zp(cpu, bus); 0 }
        0xE5 => { crate::hardware::opcodes::alu::sbc_zp(cpu, bus); 0 }
        0xE6 => { crate::hardware::opcodes::alu::inc_zp(cpu, bus); 0 }
        0xE7 => { unoff::isb_zp(cpu, bus); 0 }
        0xE8 => { crate::hardware::opcodes::alu::inx(cpu, bus); 0 }
        0xE9 => { crate::hardware::opcodes::alu::sbc_imm(cpu, bus); 0 }
        0xEA => { crate::hardware::opcodes::flow::nop(cpu, bus); 0 }
        0xEB => { unoff::sbc_unofficial(cpu, bus); 0 }
        0xEC => { crate::hardware::opcodes::alu::cpx_abs(cpu, bus); 0 }
        0xED => { crate::hardware::opcodes::alu::sbc_abs(cpu, bus); 0 }
        0xEE => { crate::hardware::opcodes::alu::inc_abs(cpu, bus); 0 }
        0xEF => { unoff::isb_abs(cpu, bus); 0 }
        0xF0 => crate::hardware::opcodes::flow::beq(cpu, bus),
        0xF1 => crate::hardware::opcodes::alu::sbc_ind_y(cpu, bus),
        0xF2 => { unoff::kil(cpu, bus); 0 }
        0xF3 => { unoff::isb_ind_y(cpu, bus); 0 }
        0xF4 => { unoff::nop_zp_x(cpu, bus); 0 }
        0xF5 => { crate::hardware::opcodes::alu::sbc_zp_x(cpu, bus); 0 }
        0xF6 => { crate::hardware::opcodes::alu::inc_zp_x(cpu, bus); 0 }
        0xF7 => { unoff::isb_zp_x(cpu, bus); 0 }
        0xF8 => { crate::hardware::opcodes::flow::sed(cpu, bus); 0 }
        0xF9 => crate::hardware::opcodes::alu::sbc_abs_y(cpu, bus),
        0xFA => { unoff::nop_implied(cpu, bus); 0 }
        0xFB => { unoff::isb_abs_y(cpu, bus); 0 }
        0xFC => unoff::nop_abs_x(cpu, bus),
        0xFD => crate::hardware::opcodes::alu::sbc_abs_x(cpu, bus),
        0xFE => { crate::hardware::opcodes::alu::inc_abs_x(cpu, bus); 0 }
        0xFF => { unoff::isb_abs_x(cpu, bus); 0 }
    }
}



