pub const NMI_VECTOR_LO: u16 = 0xFFFA;
pub const NMI_VECTOR_HI: u16 = 0xFFFB;
pub const RESET_VECTOR_LO: u16 = 0xFFFC;
pub const RESET_VECTOR_HI: u16 = 0xFFFD;
pub const IRQ_VECTOR_LO: u16 = 0xFFFE;
pub const IRQ_VECTOR_HI: u16 = 0xFFFF;

pub const STACK_BASE: u16 = 0x0100;

pub const RAM_SIZE: usize = 0x800;
pub const SYSTEM_RAM_SIZE: usize = RAM_SIZE;
pub const RAM_MIRROR_MASK: u16 = 0x07FF;
pub const PPU_REG_MIRROR_MASK: u16 = 0x2007;

pub const PPU_REG_CTRL: u16 = 0x2000;
pub const PPU_REG_MASK: u16 = 0x2001;
pub const PPU_REG_STATUS: u16 = 0x2002;
pub const PPU_REG_OAM_ADDR: u16 = 0x2003;
pub const PPU_REG_OAM_DATA: u16 = 0x2004;
pub const PPU_REG_SCROLL: u16 = 0x2005;
pub const PPU_REG_ADDR: u16 = 0x2006;
pub const PPU_REG_DATA: u16 = 0x2007;

pub const OAM_DMA: u16 = 0x4014;
pub const APU_STATUS: u16 = 0x4015;
pub const CONTROLLER1: u16 = 0x4016;
pub const CONTROLLER2: u16 = 0x4017;

pub const NAMETABLE_BASE: u16 = 0x2000;
pub const ATTRIBUTE_TABLE_BASE: u16 = 0x23C0;
pub const PALETTE_START: u16 = 0x3F00;

pub const SCROLL_HORIZONTAL_MASK: u16 = 0x041F;
pub const SCROLL_VERTICAL_MASK: u16 = 0x7BE0;
pub const COARSE_X_MASK: u16 = 0x001F;
pub const COARSE_Y_MASK: u16 = 0x03E0;
pub const FINE_Y_MASK: u16 = 0x7000;
pub const NAMETABLE_X_BIT: u16 = 0x0400;
pub const NAMETABLE_Y_BIT: u16 = 0x0800;
pub const NAMETABLE_SELECT_MASK: u16 = 0x0C00;

pub const CTRL_VRAM_INCREMENT: u8 = 0x04;
pub const CTRL_SPRITE_PATTERN: u8 = 0x08;
pub const CTRL_BG_PATTERN: u8 = 0x10;
pub const CTRL_TALL_SPRITES: u8 = 0x20;
pub const CTRL_NMI_ENABLE: u8 = 0x80;

pub const MASK_GREYSCALE: u8 = 0x01;
pub const MASK_SHOW_BG_LEFT8: u8 = 0x02;
pub const MASK_SHOW_SPRITES_LEFT8: u8 = 0x04;
pub const MASK_SHOW_BG: u8 = 0x08;
pub const MASK_SHOW_SPRITES: u8 = 0x10;
pub const MASK_EMPHASIZE_RED: u8 = 0x20;
pub const MASK_EMPHASIZE_GREEN: u8 = 0x40;
pub const MASK_EMPHASIZE_BLUE: u8 = 0x80;

pub const STATUS_SPRITE_OVERFLOW: u8 = 0x20;
pub const STATUS_SPRITE_ZERO_HIT: u8 = 0x40;
pub const STATUS_VBLANK: u8 = 0x80;

pub const SCREEN_WIDTH: usize = zeff_emu_common::system::NES_SCREEN_SIZE.0 as usize;
pub const SCREEN_HEIGHT: usize = zeff_emu_common::system::NES_SCREEN_SIZE.1 as usize;
pub const FRAMEBUFFER_LEN: usize =
    SCREEN_WIDTH * SCREEN_HEIGHT * zeff_emu_common::system::RGBA_BYTES_PER_PIXEL;
pub const PPU_DOTS_PER_SCANLINE: u16 = 341;
pub const VBLANK_START_SCANLINE: u16 = 241;
pub(crate) const PPU_PALETTE_RAM_BYTES: usize = 32;
pub(crate) const PRIMARY_OAM_BYTES: usize = 256;
pub(crate) const SECONDARY_OAM_BYTES: usize = 32;

pub const NTSC_MASTER_CLOCK_HZ_NUMERATOR: u64 = 236_250_000;
pub const NTSC_MASTER_CLOCK_HZ_DENOMINATOR: u64 = 11;
pub const PAL_MASTER_CLOCK_HZ_NUMERATOR: u64 = 53_203_425;
pub const PAL_MASTER_CLOCK_HZ_DENOMINATOR: u64 = 2;
pub const DENDY_MASTER_CLOCK_HZ_NUMERATOR: u64 = PAL_MASTER_CLOCK_HZ_NUMERATOR;
pub const DENDY_MASTER_CLOCK_HZ_DENOMINATOR: u64 = PAL_MASTER_CLOCK_HZ_DENOMINATOR;

pub const NTSC_CPU_CLOCK_HZ: f64 = NTSC_MASTER_CLOCK_HZ_NUMERATOR as f64
    / (NTSC_MASTER_CLOCK_HZ_DENOMINATOR * NTSC_MASTER_TICKS_PER_CPU_CYCLE as u64) as f64;
pub const PAL_CPU_CLOCK_HZ: f64 = PAL_MASTER_CLOCK_HZ_NUMERATOR as f64
    / (PAL_MASTER_CLOCK_HZ_DENOMINATOR * PAL_MASTER_TICKS_PER_CPU_CYCLE as u64) as f64;
pub const DENDY_CPU_CLOCK_HZ: f64 = DENDY_MASTER_CLOCK_HZ_NUMERATOR as f64
    / (DENDY_MASTER_CLOCK_HZ_DENOMINATOR * DENDY_MASTER_TICKS_PER_CPU_CYCLE as u64) as f64;
pub const APU_CPU_CLOCK_NTSC: f64 = NTSC_CPU_CLOCK_HZ;
pub const NES_DEFAULT_HOST_SAMPLE_RATE_HZ: u32 = 48_000;

pub(crate) const NTSC_MASTER_TICKS_PER_CPU_CYCLE: u8 = 12;
pub(crate) const PAL_MASTER_TICKS_PER_CPU_CYCLE: u8 = 16;
pub(crate) const DENDY_MASTER_TICKS_PER_CPU_CYCLE: u8 = 15;
pub(crate) const NTSC_MASTER_TICKS_PER_PPU_DOT: u8 = 4;
pub(crate) const PAL_MASTER_TICKS_PER_PPU_DOT: u8 = 5;
pub(crate) const DENDY_MASTER_TICKS_PER_PPU_DOT: u8 = 5;
pub(crate) const NTSC_SCANLINES_PER_FRAME: u16 = 262;
pub(crate) const PAL_SCANLINES_PER_FRAME: u16 = 312;
pub(crate) const DENDY_SCANLINES_PER_FRAME: u16 = 312;

pub const NTSC_APU_FRAME_STEP_1_CPU_CYCLE: u64 = 7457;
pub const NTSC_APU_FRAME_STEP_2_CPU_CYCLE: u64 = 14913;
pub const NTSC_APU_FRAME_STEP_3_CPU_CYCLE: u64 = 22371;
pub const NTSC_APU_FRAME_STEP_4_IRQ_START_CPU_CYCLE: u64 = 29828;
pub const NTSC_APU_FRAME_STEP_4_CLOCK_CPU_CYCLE: u64 = 29829;
pub const NTSC_APU_FRAME_STEP_4_RESET_CPU_CYCLE: u64 = 29830;
pub const NTSC_APU_FRAME_STEP_5_CPU_CYCLE: u64 = 37281;
pub const NTSC_APU_FRAME_STEP_5_RESET_CPU_CYCLE: u64 = 37282;

pub(crate) const PAL_APU_FRAME_STEP_1_CPU_CYCLE: u64 = 8313;
pub(crate) const PAL_APU_FRAME_STEP_2_CPU_CYCLE: u64 = 16627;
pub(crate) const PAL_APU_FRAME_STEP_3_CPU_CYCLE: u64 = 24939;
pub(crate) const PAL_APU_FRAME_STEP_4_IRQ_START_CPU_CYCLE: u64 = 33252;
pub(crate) const PAL_APU_FRAME_STEP_4_CLOCK_CPU_CYCLE: u64 = 33253;
pub(crate) const PAL_APU_FRAME_STEP_4_RESET_CPU_CYCLE: u64 = 33254;
pub(crate) const PAL_APU_FRAME_STEP_5_CPU_CYCLE: u64 = 41565;
pub(crate) const PAL_APU_FRAME_STEP_5_RESET_CPU_CYCLE: u64 = 41566;

pub const FRAME_STEP_1: u64 = NTSC_APU_FRAME_STEP_1_CPU_CYCLE;
pub const FRAME_STEP_2: u64 = NTSC_APU_FRAME_STEP_2_CPU_CYCLE;
pub const FRAME_STEP_3: u64 = NTSC_APU_FRAME_STEP_3_CPU_CYCLE;
pub const FRAME_STEP_4_IRQ_START: u64 = NTSC_APU_FRAME_STEP_4_IRQ_START_CPU_CYCLE;
pub const FRAME_STEP_4_CLOCK: u64 = NTSC_APU_FRAME_STEP_4_CLOCK_CPU_CYCLE;
pub const FRAME_STEP_4_RESET: u64 = NTSC_APU_FRAME_STEP_4_RESET_CPU_CYCLE;
pub const FRAME_STEP_5: u64 = NTSC_APU_FRAME_STEP_5_CPU_CYCLE;
pub const FRAME_STEP_5_RESET: u64 = NTSC_APU_FRAME_STEP_5_RESET_CPU_CYCLE;

pub const CPU_CYCLES_PER_FRAME: u64 = (NTSC_SCANLINES_PER_FRAME as u64
    * PPU_DOTS_PER_SCANLINE as u64
    * NTSC_MASTER_TICKS_PER_PPU_DOT as u64)
    .div_ceil(NTSC_MASTER_TICKS_PER_CPU_CYCLE as u64);
pub const NES_FRAME_DURATION_NS: u64 = zeff_emu_common::system::NES_FRAME_DURATION_NS;
pub const NTSC_FRAME_RATE_HZ: f64 = NTSC_MASTER_CLOCK_HZ_NUMERATOR as f64
    / NTSC_MASTER_CLOCK_HZ_DENOMINATOR as f64
    / NTSC_MASTER_TICKS_PER_PPU_DOT as f64
    / PPU_DOTS_PER_SCANLINE as f64
    / NTSC_SCANLINES_PER_FRAME as f64;

#[cfg(test)]
mod tests {
    use super::{
        FRAMEBUFFER_LEN, NES_DEFAULT_HOST_SAMPLE_RATE_HZ, NTSC_FRAME_RATE_HZ, RAM_SIZE,
        SCREEN_HEIGHT, SCREEN_WIDTH, SYSTEM_RAM_SIZE,
    };

    #[test]
    fn geometry_and_system_ram_match_their_owners() {
        assert_eq!(
            (SCREEN_WIDTH as u32, SCREEN_HEIGHT as u32),
            zeff_emu_common::system::NES_SCREEN_SIZE
        );
        assert_eq!(FRAMEBUFFER_LEN, 256 * 240 * 4);
        assert_eq!(SYSTEM_RAM_SIZE, RAM_SIZE);
        assert_eq!(SYSTEM_RAM_SIZE, 0x800);
        assert_eq!(NES_DEFAULT_HOST_SAMPLE_RATE_HZ, 48_000);
        assert!((NTSC_FRAME_RATE_HZ - 60.098_477_556_112_265).abs() < f64::EPSILON);
    }
}
