use phf::phf_map;

// Source: https://gbdev.io/pandocs/The_Cartridge_Header.html#01440145--new-licensee-code
pub(crate) static NEW_LICENSEE_MAP: phf::Map<&'static str, &'static str> = phf_map! {
    "00" => "None",
    "01" => "Nintendo R&D1",
    "08" => "Capcom",
    "13" => "Electronic Arts",
    "18" => "Hudson Soft",
    "19" => "B-AI",
    "20" => "KSS",
    "22" => "Planning Office WADA",
    "24" => "PCM Complete",
    "25" => "San-X",
    "28" => "Kemco",
    "29" => "SETA",
    "30" => "Viacom",
    "31" => "Nintendo",
    "32" => "Bandai",
    "33" => "Ocean/Acclaim",
    "34" => "Konami",
    "35" => "HectorSoft",
    "37" => "Taito",
    "38" => "Hudson Soft",
    "39" => "Banpresto",
    "41" => "Ubi Soft",
    "42" => "Atlus",
    "44" => "Malibu",
    "46" => "Angel",
    "47" => "Bullet-Proof",
    "49" => "Irem",
    "50" => "Absolute",
    "51" => "Acclaim",
    "52" => "Activision",
    "53" => "Sammy",
    "54" => "Konami",
    "55" => "Hi Tech",
    "56" => "LJN",
    "57" => "Matchbox",
    "58" => "Mattel",
    "59" => "Milton Bradley",
    "60" => "Titus",
    "61" => "Virgin",
    "64" => "LucasArts",
    "67" => "Ocean",
    "69" => "EA",
    "70" => "Infogrames",
    "71" => "Interplay",
    "72" => "Broderbund",
    "73" => "Sculptured",
    "75" => "The Sales Curve",
    "78" => "THQ",
    "79" => "Accolade",
    "80" => "Misawa",
    "83" => "LOZC",
    "86" => "Tokuma Shoten",
    "87" => "Tsukuda Original",
    "91" => "Chunsoft",
    "92" => "Video System",
    "93" => "Ocean/Acclaim",
    "95" => "Varie",
    "96" => "Yonezawa/SPal",
    "97" => "Kaneko",
    "99" => "Pack-In-Video",
    "9H" => "Bottom Up",
    "A4" => "Konami (Yu-Gi-Oh!)",
    "BL" => "MTO",
    "DK" => "Kodansha",
};

pub(crate) fn new_licensee_name(code: &str) -> &'static str {
    NEW_LICENSEE_MAP.get(code).unwrap_or(&"Unknown")
}
