[env]
CARGO_INCREMENTAL = { value = "0", force = true }

[alias]
prof = "build --profile profiling"
rp = "run --profile profiling"
tw = "test --workspace"

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=-bulk-memory"]
