use core::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NesMapper {
    Nrom,
    SxRom,
    UxRom,
    CnRom,
    TxRom,
    ExRom,
    FfeMapper6,
    AxRom,
    FfeMapper8,
    PxRom,
    FxRom,
    ColorDreams,
    FfeMapper12,
    CpRom,
    Contra100In1Function16,
    BandaiEprom24C02,
    SuperMagicCard,
    JalecoSs8806,
    Fds,
    Namco163,
    Vrc4A,
    Vrc2A,
    Vrc2B,
    Vrc6A,
    Vrc4B,
    Vrc6B,
    BnRom,
    JyAsicMapper35,
    IremG101,
    TaitoTc0190,
    Rambo1,
    IremH3001,
    GxRom,
    Sunsoft3,
    AfterBurner,
    Fme7,
    Ga23c,
    Bandai74161,
    CamericaCodemasters,
    JalecoJf17,
    Vrc3,
    PirateMmc3ChrRomChrRam2K,
    Vrc1,
    NapoleonSenki,
    HolyDiver,
    Namco109Variant,
    Nina03Or06,
    TaitoX1005,
    TaitoX1017,
    ConyYoko,
    Vrc7,
    JalecoJf13,
    J87,
    Mapper88,
    SunsoftMapper89,
    JyAsic,
    Mapper91,
    SenjouNoOokami,
    IremTamS1,
    LegacyVsVrc1,
    VsSystem,
    JalecoEarlyMapper1,
    NesEvent,
    Mapper112,
    Nina03Or06Multicart,
    TxsRom,
    TqRom,
    JalecoJf11,
    BandaiEprom24C01,
    Vrc1VsSystem,
    Subor166,
    Subor167,
    CrazyClimber,
    Sunsoft1,
    KaraokeStudio,
    CnRomWithProtectionDiodes,
    PirateMmc3ChrRomChrRam4K,
    DxRom,
    JyAsicMapper209,
    Namco175And340,
    JyAsicMapper211,
    Action52,
    CamericaCodemastersQuattro,
    Mapper240,
    Mapper242,
    WaixingF003,
    G0151,
    Mapper250,
    Mapper251,
    Other(u16),
}

impl NesMapper {
    pub const fn id(self) -> u16 {
        match self {
            Self::Nrom => 0,
            Self::SxRom => 1,
            Self::UxRom => 2,
            Self::CnRom => 3,
            Self::TxRom => 4,
            Self::ExRom => 5,
            Self::FfeMapper6 => 6,
            Self::AxRom => 7,
            Self::FfeMapper8 => 8,
            Self::PxRom => 9,
            Self::FxRom => 10,
            Self::ColorDreams => 11,
            Self::FfeMapper12 => 12,
            Self::CpRom => 13,
            Self::Contra100In1Function16 => 15,
            Self::BandaiEprom24C02 => 16,
            Self::SuperMagicCard => 17,
            Self::JalecoSs8806 => 18,
            Self::Namco163 => 19,
            Self::Fds => 20,
            Self::Vrc4A => 21,
            Self::Vrc2A => 22,
            Self::Vrc2B => 23,
            Self::Vrc6A => 24,
            Self::Vrc4B => 25,
            Self::Vrc6B => 26,
            Self::BnRom => 34,
            Self::JyAsicMapper35 => 35,
            Self::IremG101 => 32,
            Self::TaitoTc0190 => 33,
            Self::Rambo1 => 64,
            Self::IremH3001 => 65,
            Self::GxRom => 66,
            Self::Sunsoft3 => 67,
            Self::AfterBurner => 68,
            Self::Fme7 => 69,
            Self::Ga23c => 45,
            Self::Bandai74161 => 70,
            Self::CamericaCodemasters => 71,
            Self::JalecoJf17 => 72,
            Self::Vrc3 => 73,
            Self::PirateMmc3ChrRomChrRam2K => 74,
            Self::Vrc1 => 75,
            Self::NapoleonSenki => 77,
            Self::HolyDiver => 78,
            Self::Namco109Variant => 76,
            Self::Nina03Or06 => 79,
            Self::TaitoX1005 => 80,
            Self::TaitoX1017 => 82,
            Self::ConyYoko => 83,
            Self::Vrc7 => 85,
            Self::JalecoJf13 => 86,
            Self::J87 => 87,
            Self::Mapper88 => 88,
            Self::SunsoftMapper89 => 89,
            Self::JyAsic => 90,
            Self::Mapper91 => 91,
            Self::SenjouNoOokami => 94,
            Self::IremTamS1 => 97,
            Self::LegacyVsVrc1 => 98,
            Self::VsSystem => 99,
            Self::JalecoEarlyMapper1 => 92,
            Self::NesEvent => 105,
            Self::Mapper112 => 112,
            Self::Nina03Or06Multicart => 113,
            Self::TxsRom => 118,
            Self::TqRom => 119,
            Self::JalecoJf11 => 140,
            Self::BandaiEprom24C01 => 159,
            Self::Vrc1VsSystem => 151,
            Self::Subor166 => 166,
            Self::Subor167 => 167,
            Self::CrazyClimber => 180,
            Self::Sunsoft1 => 184,
            Self::KaraokeStudio => 188,
            Self::CnRomWithProtectionDiodes => 185,
            Self::PirateMmc3ChrRomChrRam4K => 192,
            Self::DxRom => 206,
            Self::JyAsicMapper209 => 209,
            Self::Namco175And340 => 210,
            Self::JyAsicMapper211 => 211,
            Self::Action52 => 228,
            Self::CamericaCodemastersQuattro => 232,
            Self::Mapper240 => 240,
            Self::Mapper242 => 242,
            Self::WaixingF003 => 245,
            Self::G0151 => 246,
            Self::Mapper250 => 250,
            Self::Mapper251 => 251,
            Self::Other(id) => id,
        }
    }

    pub const fn name(self) -> &'static str {
        match self {
            Self::Nrom => "NROM",
            Self::SxRom => "SxROM / MMC1",
            Self::UxRom => "UxROM",
            Self::CnRom => "CNROM",
            Self::TxRom => "TxROM / MMC3 / MMC6",
            Self::ExRom => "ExROM / MMC5",
            Self::FfeMapper6 => "FFE mapper 6",
            Self::AxRom => "AxROM",
            Self::FfeMapper8 => "FFE mapper 8",
            Self::PxRom => "PxROM / MMC2",
            Self::FxRom => "FxROM / MMC4",
            Self::ColorDreams => "Color Dreams",
            Self::FfeMapper12 => "FFE mapper 12",
            Self::CpRom => "CPROM",
            Self::Contra100In1Function16 => "100-in-1 Contra Function 16",
            Self::BandaiEprom24C02 => "Bandai EPROM (24C02)",
            Self::SuperMagicCard => "Super Magic Card",
            Self::JalecoSs8806 => "Jaleco SS8806",
            Self::Namco163 => "Namco 163",
            Self::Fds => "Famicom Disk System",
            Self::Vrc4A => "VRC4a / VRC4c",
            Self::Vrc2A => "VRC2a",
            Self::Vrc2B => "VRC2b / VRC4e",
            Self::Vrc6A => "VRC6a",
            Self::Vrc4B => "VRC4b / VRC4d",
            Self::Vrc6B => "VRC6b",
            Self::BnRom => "BNROM / NINA-001",
            Self::JyAsicMapper35 => "J.Y. ASIC mapper 35",
            Self::IremG101 => "Irem G-101",
            Self::TaitoTc0190 => "Taito TC0190/TC0350",
            Self::Rambo1 => "RAMBO-1",
            Self::IremH3001 => "Irem H-3001",
            Self::GxRom => "GxROM / MxROM",
            Self::Sunsoft3 => "Sunsoft-3",
            Self::AfterBurner => "After Burner",
            Self::Fme7 => "FME-7 / Sunsoft 5B",
            Self::Ga23c => "GA23C multicart",
            Self::Bandai74161 => "Bandai 74161/32",
            Self::CamericaCodemasters => "Camerica / Codemasters",
            Self::JalecoJf17 => "Jaleco JF-17",
            Self::Vrc3 => "VRC3",
            Self::PirateMmc3ChrRomChrRam2K => "Pirate MMC3 derivative (2 KiB CHR RAM)",
            Self::Vrc1 => "VRC1",
            Self::NapoleonSenki => "Napoleon Senki",
            Self::HolyDiver => "Holy Diver / Cosmo Carrier",
            Self::Namco109Variant => "Namco 109 variant",
            Self::Nina03Or06 => "NINA-03 / NINA-06",
            Self::TaitoX1005 => "Taito X1-005",
            Self::TaitoX1017 => "Taito X1-017",
            Self::ConyYoko => "Cony/Yoko",
            Self::Vrc7 => "VRC7",
            Self::JalecoJf13 => "JALECO-JF-13",
            Self::J87 => "J87",
            Self::Mapper88 => "Namco 108 variant",
            Self::SunsoftMapper89 => "Sunsoft mapper 89",
            Self::JyAsic => "J.Y. ASIC",
            Self::Mapper91 => "Mapper 91",
            Self::SenjouNoOokami => "Senjou no Ookami",
            Self::IremTamS1 => "Irem TAM-S1",
            Self::LegacyVsVrc1 => "legacy Vs. VRC1",
            Self::VsSystem => "Vs. System",
            Self::JalecoEarlyMapper1 => "Jaleco early mapper 1",
            Self::NesEvent => "NES-EVENT",
            Self::Mapper112 => "Mapper 112",
            Self::Nina03Or06Multicart => "NINA-03 / NINA-06??",
            Self::TxsRom => "TxSROM",
            Self::TqRom => "TQROM",
            Self::JalecoJf11 => "Jaleco JF-11/JF-14",
            Self::BandaiEprom24C01 => "Bandai EPROM (24C01)",
            Self::Vrc1VsSystem => "Vs. VRC1",
            Self::Subor166 => "SUBOR",
            Self::Subor167 => "SUBOR",
            Self::CrazyClimber => "Crazy Climber",
            Self::Sunsoft1 => "Sunsoft-1",
            Self::KaraokeStudio => "Karaoke Studio",
            Self::CnRomWithProtectionDiodes => "CNROM with protection diodes",
            Self::PirateMmc3ChrRomChrRam4K => "Pirate MMC3 derivative (4 KiB CHR RAM)",
            Self::DxRom => "DxROM / Namco 118 / MIMIC-1",
            Self::JyAsicMapper209 => "J.Y. ASIC mapper 209",
            Self::Namco175And340 => "Namco 175 and 340",
            Self::JyAsicMapper211 => "J.Y. ASIC mapper 211",
            Self::Action52 => "Action 52",
            Self::CamericaCodemastersQuattro => "Camerica / Codemasters Quattro",
            Self::Mapper240 => "Mapper 240",
            Self::Mapper242 => "UNL-43272",
            Self::WaixingF003 => "Waixing F003",
            Self::G0151 => "G0151",
            Self::Mapper250 => "Nitra mapper 250",
            Self::Mapper251 => "Mapper 251 / GA23C alias",
            Self::Other(_) => "Other",
        }
    }
}

impl From<u16> for NesMapper {
    fn from(value: u16) -> Self {
        match value {
            0 => Self::Nrom,
            1 => Self::SxRom,
            2 => Self::UxRom,
            3 => Self::CnRom,
            4 => Self::TxRom,
            5 => Self::ExRom,
            6 => Self::FfeMapper6,
            7 => Self::AxRom,
            8 => Self::FfeMapper8,
            9 => Self::PxRom,
            10 => Self::FxRom,
            11 => Self::ColorDreams,
            12 => Self::FfeMapper12,
            13 => Self::CpRom,
            15 => Self::Contra100In1Function16,
            16 => Self::BandaiEprom24C02,
            17 => Self::SuperMagicCard,
            18 => Self::JalecoSs8806,
            19 => Self::Namco163,
            20 => Self::Fds,
            21 => Self::Vrc4A,
            22 => Self::Vrc2A,
            23 => Self::Vrc2B,
            24 => Self::Vrc6A,
            25 => Self::Vrc4B,
            26 => Self::Vrc6B,
            34 => Self::BnRom,
            35 => Self::JyAsicMapper35,
            32 => Self::IremG101,
            33 => Self::TaitoTc0190,
            64 => Self::Rambo1,
            65 => Self::IremH3001,
            66 => Self::GxRom,
            67 => Self::Sunsoft3,
            68 => Self::AfterBurner,
            69 => Self::Fme7,
            45 => Self::Ga23c,
            70 => Self::Bandai74161,
            71 => Self::CamericaCodemasters,
            72 => Self::JalecoJf17,
            73 => Self::Vrc3,
            74 => Self::PirateMmc3ChrRomChrRam2K,
            75 => Self::Vrc1,
            77 => Self::NapoleonSenki,
            78 => Self::HolyDiver,
            76 => Self::Namco109Variant,
            79 => Self::Nina03Or06,
            80 => Self::TaitoX1005,
            82 => Self::TaitoX1017,
            83 => Self::ConyYoko,
            85 => Self::Vrc7,
            86 => Self::JalecoJf13,
            87 => Self::J87,
            88 => Self::Mapper88,
            89 => Self::SunsoftMapper89,
            90 => Self::JyAsic,
            91 => Self::Mapper91,
            92 => Self::JalecoEarlyMapper1,
            94 => Self::SenjouNoOokami,
            97 => Self::IremTamS1,
            98 => Self::LegacyVsVrc1,
            99 => Self::VsSystem,
            105 => Self::NesEvent,
            112 => Self::Mapper112,
            113 => Self::Nina03Or06Multicart,
            118 => Self::TxsRom,
            119 => Self::TqRom,
            140 => Self::JalecoJf11,
            159 => Self::BandaiEprom24C01,
            151 => Self::Vrc1VsSystem,
            166 => Self::Subor166,
            167 => Self::Subor167,
            180 => Self::CrazyClimber,
            184 => Self::Sunsoft1,
            188 => Self::KaraokeStudio,
            185 => Self::CnRomWithProtectionDiodes,
            192 => Self::PirateMmc3ChrRomChrRam4K,
            206 => Self::DxRom,
            209 => Self::JyAsicMapper209,
            210 => Self::Namco175And340,
            211 => Self::JyAsicMapper211,
            228 => Self::Action52,
            232 => Self::CamericaCodemastersQuattro,
            240 => Self::Mapper240,
            242 => Self::Mapper242,
            245 => Self::WaixingF003,
            246 => Self::G0151,
            250 => Self::Mapper250,
            251 => Self::Mapper251,
            other => Self::Other(other),
        }
    }
}

impl fmt::Display for NesMapper {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            NesMapper::Other(id) => write!(f, "Other ({id})"),
            _ => write!(f, "{} ({})", self.name(), self.id()),
        }
    }
}
