use core::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NesMapper {
    Nrom,
    SxRom,
    UxRom,
    CnRom,
    TxRom,
    ExRom,
    AxRom,
    PxRom,
    FxRom,
    ColorDreams,
    CpRom,
    Contra100In1Function16,
    BandaiEprom24C02,
    JalecoSs8806,
    Fds,
    Namco163,
    Vrc4A,
    Vrc2A,
    Vrc2B,
    Vrc6A,
    Vrc4B,
    Vrc6B,
    BnRom,
    Rambo1,
    GxRom,
    AfterBurner,
    Fme7,
    CamericaCodemasters,
    Vrc3,
    PirateMmc3ChrRomChrRam2K,
    Vrc1,
    Namco109Variant,
    Nina03Or06,
    Vrc7,
    JalecoJf13,
    SenjouNoOokami,
    NesEvent,
    Nina03Or06Multicart,
    TxsRom,
    TqRom,
    BandaiEprom24C01,
    Subor166,
    Subor167,
    CrazyClimber,
    CnRomWithProtectionDiodes,
    PirateMmc3ChrRomChrRam4K,
    DxRom,
    Namco175And340,
    Action52,
    CamericaCodemastersQuattro,
    Other(u16),
}

impl NesMapper {
    pub const fn id(self) -> u16 {
        match self {
            Self::Nrom => 0,
            Self::SxRom => 1,
            Self::UxRom => 2,
            Self::CnRom => 3,
            Self::TxRom => 4,
            Self::ExRom => 5,
            Self::AxRom => 7,
            Self::PxRom => 9,
            Self::FxRom => 10,
            Self::ColorDreams => 11,
            Self::CpRom => 13,
            Self::Contra100In1Function16 => 15,
            Self::BandaiEprom24C02 => 16,
            Self::JalecoSs8806 => 18,
            Self::Namco163 => 19,
            Self::Fds => 20,
            Self::Vrc4A => 21,
            Self::Vrc2A => 22,
            Self::Vrc2B => 23,
            Self::Vrc6A => 24,
            Self::Vrc4B => 25,
            Self::Vrc6B => 26,
            Self::BnRom => 34,
            Self::Rambo1 => 64,
            Self::GxRom => 66,
            Self::AfterBurner => 68,
            Self::Fme7 => 69,
            Self::CamericaCodemasters => 71,
            Self::Vrc3 => 73,
            Self::PirateMmc3ChrRomChrRam2K => 74,
            Self::Vrc1 => 75,
            Self::Namco109Variant => 76,
            Self::Nina03Or06 => 79,
            Self::Vrc7 => 85,
            Self::JalecoJf13 => 86,
            Self::SenjouNoOokami => 94,
            Self::NesEvent => 105,
            Self::Nina03Or06Multicart => 113,
            Self::TxsRom => 118,
            Self::TqRom => 119,
            Self::BandaiEprom24C01 => 159,
            Self::Subor166 => 166,
            Self::Subor167 => 167,
            Self::CrazyClimber => 180,
            Self::CnRomWithProtectionDiodes => 185,
            Self::PirateMmc3ChrRomChrRam4K => 192,
            Self::DxRom => 206,
            Self::Namco175And340 => 210,
            Self::Action52 => 228,
            Self::CamericaCodemastersQuattro => 232,
            Self::Other(id) => id,
        }
    }

    pub const fn name(self) -> &'static str {
        match self {
            Self::Nrom => "NROM",
            Self::SxRom => "SxROM / MMC1",
            Self::UxRom => "UxROM",
            Self::CnRom => "CNROM",
            Self::TxRom => "TxROM / MMC3 / MMC6",
            Self::ExRom => "ExROM / MMC5",
            Self::AxRom => "AxROM",
            Self::PxRom => "PxROM / MMC2",
            Self::FxRom => "FxROM / MMC4",
            Self::ColorDreams => "Color Dreams",
            Self::CpRom => "CPROM",
            Self::Contra100In1Function16 => "100-in-1 Contra Function 16",
            Self::BandaiEprom24C02 => "Bandai EPROM (24C02)",
            Self::JalecoSs8806 => "Jaleco SS8806",
            Self::Namco163 => "Namco 163",
            Self::Fds => "Famicom Disk System",
            Self::Vrc4A => "VRC4a / VRC4c",
            Self::Vrc2A => "VRC2a",
            Self::Vrc2B => "VRC2b / VRC4e",
            Self::Vrc6A => "VRC6a",
            Self::Vrc4B => "VRC4b / VRC4d",
            Self::Vrc6B => "VRC6b",
            Self::BnRom => "BNROM / NINA-001",
            Self::Rambo1 => "RAMBO-1",
            Self::GxRom => "GxROM / MxROM",
            Self::AfterBurner => "After Burner",
            Self::Fme7 => "FME-7 / Sunsoft 5B",
            Self::CamericaCodemasters => "Camerica / Codemasters",
            Self::Vrc3 => "VRC3",
            Self::PirateMmc3ChrRomChrRam2K => "Pirate MMC3 derivative (2 KiB CHR RAM)",
            Self::Vrc1 => "VRC1",
            Self::Namco109Variant => "Namco 109 variant",
            Self::Nina03Or06 => "NINA-03 / NINA-06",
            Self::Vrc7 => "VRC7",
            Self::JalecoJf13 => "JALECO-JF-13",
            Self::SenjouNoOokami => "Senjou no Ookami",
            Self::NesEvent => "NES-EVENT",
            Self::Nina03Or06Multicart => "NINA-03 / NINA-06??",
            Self::TxsRom => "TxSROM",
            Self::TqRom => "TQROM",
            Self::BandaiEprom24C01 => "Bandai EPROM (24C01)",
            Self::Subor166 => "SUBOR",
            Self::Subor167 => "SUBOR",
            Self::CrazyClimber => "Crazy Climber",
            Self::CnRomWithProtectionDiodes => "CNROM with protection diodes",
            Self::PirateMmc3ChrRomChrRam4K => "Pirate MMC3 derivative (4 KiB CHR RAM)",
            Self::DxRom => "DxROM / Namco 118 / MIMIC-1",
            Self::Namco175And340 => "Namco 175 and 340",
            Self::Action52 => "Action 52",
            Self::CamericaCodemastersQuattro => "Camerica / Codemasters Quattro",
            Self::Other(_) => "Other",
        }
    }
}

impl From<u16> for NesMapper {
    fn from(value: u16) -> Self {
        match value {
            0 => Self::Nrom,
            1 => Self::SxRom,
            2 => Self::UxRom,
            3 => Self::CnRom,
            4 => Self::TxRom,
            5 => Self::ExRom,
            7 => Self::AxRom,
            9 => Self::PxRom,
            10 => Self::FxRom,
            11 => Self::ColorDreams,
            13 => Self::CpRom,
            15 => Self::Contra100In1Function16,
            16 => Self::BandaiEprom24C02,
            18 => Self::JalecoSs8806,
            19 => Self::Namco163,
            20 => Self::Fds,
            21 => Self::Vrc4A,
            22 => Self::Vrc2A,
            23 => Self::Vrc2B,
            24 => Self::Vrc6A,
            25 => Self::Vrc4B,
            26 => Self::Vrc6B,
            34 => Self::BnRom,
            64 => Self::Rambo1,
            66 => Self::GxRom,
            68 => Self::AfterBurner,
            69 => Self::Fme7,
            71 => Self::CamericaCodemasters,
            73 => Self::Vrc3,
            74 => Self::PirateMmc3ChrRomChrRam2K,
            75 => Self::Vrc1,
            76 => Self::Namco109Variant,
            79 => Self::Nina03Or06,
            85 => Self::Vrc7,
            86 => Self::JalecoJf13,
            94 => Self::SenjouNoOokami,
            105 => Self::NesEvent,
            113 => Self::Nina03Or06Multicart,
            118 => Self::TxsRom,
            119 => Self::TqRom,
            159 => Self::BandaiEprom24C01,
            166 => Self::Subor166,
            167 => Self::Subor167,
            180 => Self::CrazyClimber,
            185 => Self::CnRomWithProtectionDiodes,
            192 => Self::PirateMmc3ChrRomChrRam4K,
            206 => Self::DxRom,
            210 => Self::Namco175And340,
            228 => Self::Action52,
            232 => Self::CamericaCodemastersQuattro,
            other => Self::Other(other),
        }
    }
}

impl fmt::Display for NesMapper {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            NesMapper::Other(id) => write!(f, "Other ({id})"),
            _ => write!(f, "{} ({})", self.name(), self.id()),
        }
    }
}
