use winit::keyboard::KeyCode;

pub(crate) fn keycode_to_string(code: KeyCode) -> String {
    format!("{code:?}")
}

static KEYCODE_MAP: phf::Map<&'static str, KeyCode> = phf::phf_map! {
    "ArrowUp" => KeyCode::ArrowUp,
    "ArrowDown" => KeyCode::ArrowDown,
    "ArrowLeft" => KeyCode::ArrowLeft,
    "ArrowRight" => KeyCode::ArrowRight,
    "Enter" => KeyCode::Enter,
    "ShiftLeft" => KeyCode::ShiftLeft,
    "ShiftRight" => KeyCode::ShiftRight,
    "ControlLeft" => KeyCode::ControlLeft,
    "ControlRight" => KeyCode::ControlRight,
    "AltLeft" => KeyCode::AltLeft,
    "AltRight" => KeyCode::AltRight,
    "Space" => KeyCode::Space,
    "Backspace" => KeyCode::Backspace,
    "Escape" => KeyCode::Escape,
    "Tab" => KeyCode::Tab,
    "CapsLock" => KeyCode::CapsLock,
    "Minus" => KeyCode::Minus,
    "Equal" => KeyCode::Equal,
    "BracketLeft" => KeyCode::BracketLeft,
    "BracketRight" => KeyCode::BracketRight,
    "Backslash" => KeyCode::Backslash,
    "Semicolon" => KeyCode::Semicolon,
    "Quote" => KeyCode::Quote,
    "Comma" => KeyCode::Comma,
    "Period" => KeyCode::Period,
    "Slash" => KeyCode::Slash,
    "Backquote" => KeyCode::Backquote,
    "KeyA" => KeyCode::KeyA,
    "KeyB" => KeyCode::KeyB,
    "KeyC" => KeyCode::KeyC,
    "KeyD" => KeyCode::KeyD,
    "KeyE" => KeyCode::KeyE,
    "KeyF" => KeyCode::KeyF,
    "KeyG" => KeyCode::KeyG,
    "KeyH" => KeyCode::KeyH,
    "KeyI" => KeyCode::KeyI,
    "KeyJ" => KeyCode::KeyJ,
    "KeyK" => KeyCode::KeyK,
    "KeyL" => KeyCode::KeyL,
    "KeyM" => KeyCode::KeyM,
    "KeyN" => KeyCode::KeyN,
    "KeyO" => KeyCode::KeyO,
    "KeyP" => KeyCode::KeyP,
    "KeyQ" => KeyCode::KeyQ,
    "KeyR" => KeyCode::KeyR,
    "KeyS" => KeyCode::KeyS,
    "KeyT" => KeyCode::KeyT,
    "KeyU" => KeyCode::KeyU,
    "KeyV" => KeyCode::KeyV,
    "KeyW" => KeyCode::KeyW,
    "KeyX" => KeyCode::KeyX,
    "KeyY" => KeyCode::KeyY,
    "KeyZ" => KeyCode::KeyZ,
    "Digit0" => KeyCode::Digit0,
    "Digit1" => KeyCode::Digit1,
    "Digit2" => KeyCode::Digit2,
    "Digit3" => KeyCode::Digit3,
    "Digit4" => KeyCode::Digit4,
    "Digit5" => KeyCode::Digit5,
    "Digit6" => KeyCode::Digit6,
    "Digit7" => KeyCode::Digit7,
    "Digit8" => KeyCode::Digit8,
    "Digit9" => KeyCode::Digit9,
    "F1" => KeyCode::F1,
    "F2" => KeyCode::F2,
    "F3" => KeyCode::F3,
    "F4" => KeyCode::F4,
    "F5" => KeyCode::F5,
    "F6" => KeyCode::F6,
    "F7" => KeyCode::F7,
    "F8" => KeyCode::F8,
    "F9" => KeyCode::F9,
    "F10" => KeyCode::F10,
    "F11" => KeyCode::F11,
    "F12" => KeyCode::F12,
    "Pause" => KeyCode::Pause,
};

pub(crate) fn keycode_from_string(name: &str) -> Option<KeyCode> {
    KEYCODE_MAP.get(name).copied()
}

